### ISSUE TITLE
php artisan module: seed Not working

### ISSUE THREAD

**Issue by githubmarau** [nWidart/laravel-modules#465] opened 2018-01-19 02:22 UTC
Hi, I've tried everything, the same error occurs.

"  In SeedCommand.php line 177:

  Type error: Argument 1 passed to Nwidart\Modules\Commands\SeedCommand::reportException() must be an instance of Exception, instance of Er
  ror given, called in F:\laragon\www\rhema\vendor\nwidart\laravel-modules\src\Commands\SeedCommand.php on line 50  "

<?php
namespace Modules\User\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Modules\User\Database\Seeders\UserTableSeeder;

class UserDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        //$this->call("UserTableSeeder");
        
        User::create([
            'name' => 'Admin',
            'email' => 'admin@admin.com',
            'password' => bcrypt(123456)
        ]);
    }
}

Could someone help me?

I've tried creating the UserTableSeeder class but the same error occurs.

**Comment by raakesh** [comment] 2018-02-02 05:04
I'm getting same error

`  Type error: Argument 1 passed to Nwidart\Modules\Commands\SeedCommand::reportException() must be an instance of Exception, instance of Error given, called in /home/vagrant/sites/perfqube/
  vendor/nwidart/laravel-modules/src/Commands/SeedCommand.php on line 50
`

**Comment by raakesh** [comment] 2018-02-02 05:06
Unable to seed Module based seeders.

**Comment by andrietri** [comment] 2018-02-02 11:35
im get same error

**Comment by nWidart** [comment] 2018-02-02 12:01
Feel free to send a pull request guys :)

**Comment by iahmad** [comment] 2018-02-05 10:17
for now I do it like so:

`php artisan db:seed --class=\\Modules\\Mymodule\\Database\\Seeders\\MymoduleDatabaseSeeder`

**Comment by nWidart** [comment] 2018-02-06 20:22
I was able to run the `module:seed` command with no issues here. How exactly could I reproduce the issue?

**Comment by alisonvalente** [comment] 2018-02-07 01:34
I had the same problem when following laravel documentation; then I realized I forgot to **use** the DB class. 
On UserDatabaseSeeder.php:

**use Illuminate\Support\Facades\DB;**

Works for me =)

**Comment by h4ckedneko** [comment] 2018-02-13 05:59
I think it's because `Error` does not inherit from `Exception` in PHP 7. But both of them inherit from `Throwable`, however it is not supported on PHP 5.

Laravel still uses `Exception` rather than `Throwable` in their handler. Maybe in the future, when Laravel is in pure PHP 7.

See [http://php.net/manual/en/language.errors.php7.php](http://php.net/manual/en/language.errors.php7.php).

**Comment by treetechsuman** [comment] 2018-03-29 10:09
Seeding: Modules\Package\Database\Seeders\PackageDataSeeders

In SeedCommand.php line 177:

  Type error: Argument 1 passed to Nwidart\Modules\Commands\SeedCommand::repo
  rtException() must be an instance of Exception, instance of Error given, ca
  lled in C:\wamp64\www\wprojects\travel\vendor\nwidart\laravel-modules\src\C
  ommands\SeedCommand.php on line 50

**Comment by krysal** [comment] 2018-04-17 15:26
Why was changed the namespace of created seeders from $NAMESPACE$\Database\Seeders; to namespace $NAMESPACE$;?

**Comment by nWidart** [comment] 2018-04-26 07:25
This is getting replaced by the command now.

I'll close this as it was fixed. If not feel free to re-comment and I'll re-open.

**Closed by nWidart** 2018-04-26 07:25 UTC

**Comment by jayadevkv** [comment] 2018-06-19 08:23
Issue still there on release 2.7.0. I am using laravel 5.5 with php 7.2.6.

**Comment by crmsoft** [comment] 2018-06-30 09:42
+1

**Comment by nasirkhan** [comment] 2018-07-02 10:40
facing same issue. Anyone have a complete example to the workaround or solution of the issue?

**Comment by renfan** [comment] 2018-07-07 03:31
+1

**Comment by rolandalla** [comment] 2018-09-25 11:12
Same issue with Laravel 5.6 and php 7.2*

**Comment by mbrown1408** [comment] 2018-10-07 07:56
Appears to be the same issue with L5.7 php 7.2 - when seeding.

Argument 1 passed to NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::report() must be an instance of Exception, instance of Error given, called in /home/dev/public_html/vendor/nwidart/laravel-modules/src/Commands/SeedCommand.php on line 180

**Comment by robov** [comment] 2018-12-06 20:08
Just to add some thoughts.. I had the same thing today.... while I KNEW it worked yesterday... so I could easily backtrack the changes. Apparently there was a syntax error in my ModuleSeeder.php.
After fixing the syntax error it worked again

**Comment by numerical25** [comment] 2018-12-07 13:20
well @robov I definitely took in what you said and that definitely was my issue as well. It appears my class  `$lipsum = new joshtronic\LoremIpsum();` needed to add the backslash at the beginning like so `$lipsum = new \joshtronic\LoremIpsum();` . In conclusion I would say anyone who has this issue more then likely has a error some where in their document. The Exception just probably needs to be caught and logged to know specifically what it is.

**Comment by mehmetilhan** [comment] 2019-01-05 09:50
**Change** $this->call("LanguagesTableSeeder"); **to** $this->call(LanguagesTableSeeder::class);
**and** php artisan module:seed <_ModuleName_>

**Comment by amitshahc** [comment] 2019-01-09 09:02
I also faced the same issues listed above with similar errors.. 
after few tries, i was able to run the seeder in the Modules/dashboard successfully. 

ContactsFactory.php

```
<?php

use Faker\Generator as Faker;

$factory->define(Modules\Dashboard\Entities\Contacts::class, function (Faker $faker) {
    return [
        'name' => $faker->name,
        'email' => $faker->unique()->safeEmail,
        'phone' => $faker->e164PhoneNumber,
        'age' => $faker->numberBetween(18, 55),
        'gender' => $faker->randomElement($array = array ('male','female','other'))
    ];
});
```

ContactsTableSeeder.php
```
<?php

namespace Modules\Dashboard\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Modules\Dashboard\Entities\Contacts;

class ContactsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $contacts = factory(Contacts::class, 35000)->create();
        //Model::unguard();
        // $this->call("OthersTableSeeder");
    }
}

```

DashboardDatabaseSeeder.php (Main seeder file in Modules/dashboard)
```
<?php

namespace Modules\Dashboard\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class DashboardDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $this->call("Modules\Dashboard\Database\Seeders\ContactsTableSeeder");
    }
}

```

**Comment by bondril13** [comment] 2019-07-11 05:15
I try to use  "use Illuminate\Support\Facades\DB;"
but didn't work

then i try to use back slash, it work for me
`\DB::table('...')->insert([...`

**Comment by juneX05** [comment] 2019-07-14 11:37
I really do not understand too why the error keeps repeating. @nWidart please help us out on how to remove the error. Even the seeder classes generated with the module:make-seed get the **Class reflection error** 

Until then a temporary fix is to just use the seeder generated in the module and not otherwise.
Also for all those who are getting the exception or throwable errors please be sure to check your models first. Seeding a module that has a dependency on another module will always give you the throwable error.

**Comment by hasanali05** [comment] 2019-11-19 18:41
I faced the same problem. After some moment I figured out one thing, I missed one of my used Model. 

@nWidart, In that case, it should say, the model 'Tried_to_create_data' is not found.

**Comment by wakjoko** [comment] 2020-08-05 14:32
hey guys,

i got it my custom seeder class working.

to insert seeded data you'll need to define it in `module.json`
```
{
    "name": "Rates",
    "alias": "rates",
    .
    .
    .
    "migration": {
        "seeds": [
            "Modules\\Rates\\database\\seeds\\v1\\DatabaseSeeder"
        ]
    }
}
```

then run command
`php artisan module:seed Rates` to seed all the seeders defined there or
`php artisan module:seed Rates --class=DatabaseSeeder` to seed one single seeder.

the key here is to define your seeder classes in `module.json`

i suppose this should be added to the docs as well @nWidart

**Comment by saber13812002** [comment] 2020-10-12 15:26
php artisan db:seed --class=WM\Common\Seeder\SmsStatusSeeder

**Comment by andreshg112** [comment] 2021-08-04 13:57
I guess this should be documented. When using subfolders, you can specify the seeders in the file module.json. I realized about it by digging through the code.

<img width="924" alt="image" src="https://user-images.githubusercontent.com/15859884/128193488-da35220a-0207-4712-9cf5-9a5a9b324997.png">

**Comment by ctf0** [comment] 2022-10-11 10:15
@andreshg112 thanks for the tip, apprently in order for the seeders to be discoverd, we have to have a `ModuleNameDatabaseSeeder` where u add ur seeders using `$this->call()` like the default in laravel for the cmnd to run as expected.

**Comment by OsmairCoelhoGY** [comment] 2023-05-31 14:13
in 2023 any solution for this issue?
![image](https://github.com/nWidart/laravel-modules/assets/134397238/ffe27138-5997-4f30-b8fe-8b16f9d003b1)

**Comment by danarn17** [comment] 2024-02-27 08:04
it's 2024 and i face the same problem. And why sometimes it generate with capital on first letter, and sometimes not. i do both on same OS.
![image](https://github.com/nWidart/laravel-modules/assets/39963063/052e0170-587d-4a63-97cd-cfaee14c3900)

**Comment by parastooam** [comment] 2024-11-26 09:33
Thank you @andreshg112 it worked
