### ISSUE TITLE
PHP Fatal error:  Call to a member function getStudlyName()

### ISSUE THREAD

**Issue by himalaya-ahuja** [nWidart/laravel-modules#342] opened 2017-09-20 06:18 UTC
Hi I have been using this Package for quite some time now , it was working fine until suddenly this morning i encountered this error while refreshing the migrations for my module "Admin".
Ran this command:  php artisan module:migrate-refresh Admin
Got this error stack trace in console: 

Call to a member function getStudlyName() on string in /home/himalaya/Documents/work/laravel/e-commerce/vendor/nwidart/laravel-modules/src/Commands/MigrateRefreshCommand.php on line 88
                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Call to a member function getStudlyName() on string     

I don't understand what went wrong , i changed nothing.

**Comment by nWidart** [comment] 2017-09-22 10:06
Hello,

I just tried this command locally and wasn't able to reproduce it.
Looking at the code where it's failing for you, it might be because of a non-existing module.
Though even if I called a non existing module, it will run for all modules.

**Comment by himalaya-ahuja** [comment] 2017-09-23 13:44
The module is active i checked and all the other commands related to this module are working fine , this too was working fine before until now..

**Comment by nWidart** [comment] 2017-10-03 12:24
I'll close this for now.

**Closed by nWidart** 2017-10-03 12:24 UTC
