### ISSUE TITLE
need update for laravel 8

### ISSUE THREAD

**Issue by faguvenli** [nWidart/laravel-modules#1050] opened 2020-09-09 13:48 UTC
Hello;
need some changes about the file system for laravel 8. 
When a new module created it looks for [Illuminate\Database\Eloquent\Factories\Factory] but in laravel 8 it is changed to Illuminate\Database\Eloquent\Factories\Factory.

**Comment by midhunmonachan** [comment] 2020-09-10 01:37
I had this issue too
`C:\Users\Midhun\Documents\GitHub\Mastery>composer dump-autoload
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Illuminate\Contracts\Container\BindingResolutionException

  Target [Illuminate\Database\Eloquent\Factories\Factory] is not instantiable.

  at C:\Users\Midhun\Documents\GitHub\Mastery\vendor\laravel\framework\src\Illuminate\Container\Container.php:1017
    1013▕         } else {
    1014▕             $message = "Target [$concrete] is not instantiable.";
    1015▕         }
    1016▕
  ➜ 1017▕         throw new BindingResolutionException($message);
    1018▕     }
    1019▕
    1020▕     /**
    1021▕      * Throw an exception for an unresolvable primitive.

  1   C:\Users\Midhun\Documents\GitHub\Mastery\vendor\laravel\framework\src\Illuminate\Container\Container.php:818
      Illuminate\Container\Container::notInstantiable("Illuminate\Database\Eloquent\Factories\Factory")

  2   C:\Users\Midhun\Documents\GitHub\Mastery\vendor\laravel\framework\src\Illuminate\Container\Container.php:691
      Illuminate\Container\Container::build("Illuminate\Database\Eloquent\Factories\Factory")
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

I changed line 6 of {ModuleName}\Providers\{ModuleName}ServiceProvider.php file from `use Illuminate\Database\Eloquent
Duplicate of #\Factory;` to `use Illuminate\Database\Eloquent\Factories\Factory;`

**Comment by Plasto13** [comment] 2020-09-11 07:54
Same problem.
I changed use [Illuminate\Database\Eloquent\Factory;] to [use Illuminate\Database\Eloquent\Factories\Factory;]
 Illuminate\Contracts\Container\BindingResolutionException

  Target [Illuminate\Database\Eloquent\Factories\Factory] is not instantiable.

  at C:\xampp\htdocs\laravel-modular\vendor\laravel\framework\src\Illuminate\Con
tainer\Container.php:1017
    1013▕         } else {
    1014▕             $message = "Target [$concrete] is not instantiable.";
    1015▕         }
    1016▕
  ➜ 1017▕         throw new BindingResolutionException($message);
    1018▕     }
    1019▕
    1020▕     /**
    1021▕      * Throw an exception for an unresolvable primitive.

  1   C:\xampp\htdocs\laravel-modular\vendor\laravel\framework\src\Illuminate\Co
ntainer\Container.php:818
      Illuminate\Container\Container::notInstantiable("Illuminate\Database\Eloqu
ent\Factories\Factory")

  2   C:\xampp\htdocs\laravel-modular\vendor\laravel\framework\src\Illuminate\Co
ntainer\Container.php:691
      Illuminate\Container\Container::build("Illuminate\Database\Eloquent\Factor
ies\Factory")

**Comment by Plasto13** [comment] 2020-09-11 08:52
possible solution ??..
```
  /**
     * Register an additional directory of factories.
     *
     * @return void
     */
    public function registerFactories()
    {
        if (! app()->environment('production') && $this->app->runningInConsole()) {
            $this->loadFactoriesFrom(module_path($this->moduleName, 'Database/factories'));
        }
    }
```

**Comment by rajakhoury** [comment] 2020-09-11 13:24
@Plasto13 I think this workaround needs the [laravel/legacy-factories](https://github.com/laravel/legacy-factories) package because the ones generated are not factories classes also the models should include the factories trait by default. 

@nWidart Is there a release time for the L8 upgrade?

**Comment by midhunmonachan** [comment] 2020-09-12 01:30
#1059 Try this.

**Comment by roldandvg** [comment] 2020-09-15 14:57
hello, is there an approximate date planned for the support update to laravel 8 ?, thanks

**Comment by jobrajankallumala** [comment] 2020-09-19 18:06
> #1057.

**Comment by jobrajankallumala** [comment] 2020-09-19 18:10
This

> #1057.
This have helped me to solve the issue.
But need permeant solution by support release to Laravel 8.
Thank you.

**Comment by truesteps** [comment] 2020-09-29 13:25
!!!the `loadFactoriesFrom` method should not be used since it will be removed from Laravel in a future version!!!

What you should do, is overwrite the `protected static function newFactory` method, that the HasFactory trait provides, and just register the factory there. I would be happier for a more "global" solution but this seems to be a good solution and doing it the way laravel intended it to. Hacking stuff will bite you in the future :)

**Comment by nWidart** [comment] 2020-10-03 15:01
Support has been added.

**Closed by nWidart** 2020-10-03 15:01 UTC

**Comment by suryakaritva** [comment] 2024-02-10 18:40
Can someone advise the solution to this problem? 
`  Class Illuminate\Database\Eloquent\Factory does not exist  `

I am working on an upgrade from laravel 7 to 8 and bumped into this problem.
nWidart mentioned above support has been added. What does this mean, shouldn't we get this problem anymore or we need to use laravel/legacy-factories to overcome this error.

Please clarify. thanks. :)

**Comment by dcblogdev** [comment] 2024-02-10 18:44
either install legacy package or update your factories to use the modern class based versions.
