### ISSUE TITLE
Laravel 5.5.13 - mergeConfigFrom() error

### ISSUE THREAD

**Issue by heliomoreira** [nWidart/laravel-modules#358] opened 2017-09-27 00:00 UTC
After update to laravel 5.5.13 and nwidart modules v2.3.0 and create an module, I get this error:

Illuminate\Support\ServiceProvider::mergeConfigFrom(): Failed opening required 'C:\MAMP\htdocs\dev\Modules\Dashboard\Providers/../$PATH_CONFIG$/config.php' (include_path='.;C:\php\pear')

**Comment by nWidart** [comment] 2017-09-27 07:27
Hello,

I've just tried to reproduce this on a clean laravel install and I was able to generate a new module and publish the configuration without any errors.

From your errors, it seems to be an environment issue.

**Comment by mickacz** [comment] 2017-09-27 09:26
I have the same problem.
There is a bug in the module generator.
After creating Module ServiceProvider it looks like this:

```php
protected function registerConfig()
{
	$this->publishes([
		__DIR__.'/../$PATH_CONFIG$/config.php' => config_path('$LOWER_NAME$.php'),
	], 'config');
	$this->mergeConfigFrom(
		__DIR__.'/../$PATH_CONFIG$/config.php', '$LOWER_NAME$'
	);
}

public function registerViews()
{
	$viewPath = resource_path('views/modules/$LOWER_NAME$');

	$sourcePath = __DIR__.'/../$PATH_VIEWS$';

	$this->publishes([
		$sourcePath => $viewPath
	]);

	$this->loadViewsFrom(array_merge(array_map(function ($path) {
		return $path . '/modules/$LOWER_NAME$';
	}, \Config::get('view.paths')), [$sourcePath]), '$LOWER_NAME$');
}
```

**Comment by nWidart** [comment] 2017-09-27 09:32
Thanks, I see. I was able to replicate this.

It must be something due to the latest changes in PR #354  by @Kyslik

**Comment by nWidart** [comment] 2017-09-27 09:38
Working on the fix now & writing a test to make sure it doesn't happen again. Expect a new version soon.

**Comment by Kyslik** [comment] 2017-09-27 09:47
I can take a look at it later tonight (in 7 hours from now) if its not fixed until then.

Tests passed, but new ones are needed I guess :)

**Comment by nWidart** [comment] 2017-09-27 09:50
I got the fix locally. 👍 

I'm now integrating https://github.com/spatie/phpunit-snapshot-assertions to allow easier testing of file contents.

**Comment by nWidart** [comment] 2017-09-27 12:40
Released in [2.4](https://github.com/nWidart/laravel-modules/releases/tag/2.4.0)

**Closed by nWidart** 2017-09-27 12:40 UTC

**Comment by Kyslik** [comment] 2017-09-28 07:11
Can you please point out exact commit that fixed it; if you remember from top of your head?
I am just curious if I had broke it.

**Comment by nWidart** [comment] 2017-09-28 07:13
It was this part: https://github.com/nWidart/laravel-modules/pull/354/files#diff-0821ff0b93f8baa105b780209060fe92L71

By removing all the things to look for the data was not getting replaced in the stubs.

**Comment by Kyslik** [comment] 2017-09-28 07:22
Oh wow! That sure is my bad, I thought its used only for the stub generation (and tests passed). Will have to take a closer look how exactly that works.

Thanks.

**Comment by nWidart** [comment] 2017-09-28 07:23
Yea sorry it's my bad too, the tests for the provider checked that the provider was created, but not its (full) content. 
This has now been fixed and the full content is checked for every generated file.
