### ISSUE TITLE
ExceptionHandler::report() mu st be an instance of Exception

### ISSUE THREAD

**Issue by Alercard** [nWidart/laravel-modules#574] opened 2018-07-02 20:22 UTC
I'm working with seeds, but I got this error message:

"Symfony\Component\Debug\Exception\FatalThrowableError  : Type error: Argument
 1 passed to NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::report() mu
st be an instance of Exception, instance of Error given, called in C:\proyectos\
laravel\onyx\vendor\nwidart\laravel-modules\src\Commands\SeedCommand.php on line
 179"

I don't understand this issue, because I can't read the real error message and I don't know what happens!

I'm using Laravel 5.6 and nwidart/laravel-modules v3.0

It falls in this instruction: $profile->options()->sync($options);

Thanks for your help!

**Comment by nWidart** [comment] 2018-07-02 20:55
Hi,

What version of php are you using?

Ps: There is no need to post this in collision.

**Comment by Alercard** [comment] 2018-07-02 21:04
My php version is 7.2.5

I found in SeedCommand.php file, on handle function, in catch section, param $e is an Error class, not an Exception class and that trigger a new exception who shows me another error message.

That Error class, shows me the true error. I hope this can helps to solve this issue!

**Comment by Alercard** [comment] 2018-07-02 21:18
By the way, thanks for this plugin!

**Comment by Alercard** [comment] 2018-07-02 21:46
Ok, I'll explain what happens.

1. I created two models for a ManyToMany relationship. In this case, Profile and Option Models. I used "php artisan module:make-model ..." instruction
2. In Profile.php, I reference to Option Model by "use Option;" instruction and I wrote the function:
    public function options()
    {
    	return $this->belongsToMany(Option::class, 'sec_permissions', 'profile_id','option_id')->withTimestamps();
    }

3. When I use "$profile->options()->sync($options);" intruction in the seeder php file, that generate the Error class. In this case, the error class said: "Class Option not founded", so I replaced the instruction "use Option;" for "use Modules\Security\Entities\Option;" and this solve my true issue.

I hope with theese instructions helps to reproduce this issue.

**Comment by ebisbal** [comment] 2018-07-05 13:36
The solution i proposed in issue #579 is that you must change functions **renderException** and **reportException**. In that functions, they receive a **Throwable object $e** which is passed to functions **renderForConsole** and **report** but this functions need to receive an **Exception object**. Then you must cast the Throwable object to an Exception object.

**Comment by marcelogarbin** [comment] 2018-07-09 15:37
Same problem here, did you correct?

**Comment by aios** [comment] 2018-08-08 21:09
Same problem. @nWidart  Maybe i can make an fix PR?

**Comment by nWidart** [comment] 2018-08-10 07:54
@aios of course yes. 👍

**Comment by aios** [comment] 2018-08-10 09:06
@nWidart i looked at here your answer - fine - i must work with it.

**Comment by sthaiya** [comment] 2019-01-22 23:14
I can confirm this is still an issue with latest version (v4.0.0) on laravel 5.7 and PHP 7.1.26

**Comment by mrcage** [comment] 2019-02-03 20:35
Same for me, issue still exists

**Comment by pankajsanam** [comment] 2019-03-26 06:44
> @nWidart i looked at here your answer - fine - i must work with it.

Hey man, are you still working on a PR for this?

Do you see a solution other than #598? I tried but couldn't find any other solution than changing the Throwable to Exception in the handle method and reportException parameter.

**Comment by nWidart** [comment] 2019-03-26 08:29
The ultimate solution is to not have an error in your migration 😄

**Comment by pankajsanam** [comment] 2019-03-26 08:40
It's like suggesting somebody not to drive a car to avoid accidents. :laughing: 

Just kidding man.

I love this package and hopefully, this gets fixed because a lot of first-time users might be scratching their heads to figure this out.

Although it is always a silly mistake that lands everyone to this error.

**Comment by mrcage** [comment] 2019-04-01 15:07
Agree with @pankajsanam ; of course its goood to have no errors in migrations, but if there is an issue, its soo much easier to debug if there is the appropriate error message. With the current status, not even anayzing the stack trace in the laravel.log helps nail down the issue.

**Comment by nWidart** [comment] 2019-04-02 08:28
Don't get me wrong I'd like to have this fixed, but currently, the proposed solutions don't fully solve the issue.

**Comment by stephandesouza** [comment] 2019-04-02 12:32
@nWidart may i help you with this

**Comment by stephandesouza** [comment] 2019-04-02 12:42
Reply from #744, but what are you expecting than?

Laravel renderForConsole() and report() only accepts `Exception` which implements `Throwable`. But not all `Throwable` instance are in fact `Exception` because internal PHP errors throws `Error` (example used).

**Comment by nWidart** [comment] 2019-04-02 12:43
Well if I knew the issue wouldn't exist anymore.

I know that there was first `Exception` , then `Throwable`, then back, etc. never fully fixing the issue.

**Comment by stephandesouza** [comment] 2019-04-02 12:47
Remove the try/catch exception from `handle()` method than and leave to Framework to manager this, is not a solution?

**Comment by web2sign** [comment] 2019-04-30 08:44
I had this problem... I dont get this error on other module except for Ads module O_O

**Comment by nWidart** [comment] 2019-04-30 09:35
It means you have some error (like a syntax error) in a migration of this module.

**Comment by web2sign** [comment] 2019-04-30 15:11
> It means you have some error (like a syntax error) in a migration of this module.

Yeah I've found the culprit earlier it a misspelled Carbon ugh

use Carbom\Carbon;

**Comment by badrul1329** [comment] 2019-06-12 07:32
@nWidart  is this really solved? i'm getting the error in Laravel Modules v5.0, i am using laravel v5.8.18. 
What's the permanent solution of this error?

**Comment by nWidart** [comment] 2019-06-12 07:39
It's not solved, and don't have a solution yet, hence the open status of this ticket.

**Comment by emmanuelleabendan** [comment] 2019-08-15 13:37
I just had this same error 

Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::report() must be an instance of Exc
eption, instance of Error given, called in C:\Users\evabendan.STRAIGHTARROW\Documents\Laravel\official-tinysteps\tinysteps\tinysteps\vendor\nwidart\laravel-modules\src\Commands\SeedCommand.php
 on line 211

All I did is reference the Model at the top

Example: 
use Modules\Admin\Entities\Modelname;

And everything works.

**Comment by nWidart** [comment] 2019-10-15 11:15
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Closed by nWidart** 2019-10-15 11:15 UTC
Labels: help wanted

**Comment by mnestorov** [comment] 2019-10-23 11:41
> I just had this same error
> 
> Symfony\Component\Debug\Exception\FatalThrowableError : Argument 1 passed to NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::report() must be an instance of Exc
> eption, instance of Error given, called in .....
> 
> All I did is reference the Model at the top
> 
> Example:
> use Modules\Admin\Entities\Modelname;
> 
> And everything works.

I can confirm that
