### ISSUE TITLE
Have you planned to add livewire all features by default? If not, how can I use livewire into this package?

### ISSUE THREAD

**Issue by mhmiton** [nWidart/laravel-modules#1023] opened 2020-07-14 20:01 UTC
Hi, I want to use livewire all features with this package. Can you add livewire command things? If you have not to plan with this, just suggest me a proper way to use livewire in this package. Thanks.

**Comment by nWidart** [comment] 2020-07-14 20:02
Hi,

This is a duplicate of : https://github.com/nWidart/laravel-modules/issues/1021

**Closed by nWidart** 2020-07-14 20:02 UTC
