### ISSUE TITLE
Laravel default routes should not overwrite (additional / any?) Module Route

### ISSUE THREAD

**Issue by macwinnie** [nWidart/laravel-modules#670] opened 2018-11-26 06:19 UTC
Hi @nWidart,

I struggled about a problem with routes of a module overwritten by the default Laravel ones ... therefor I first just commented beneath Issue #19, but now created a new one.

Let the Laravel app be available at `example.com` (1).
I've implemented a second domain to my Laravel-Application, so `subdomain.example.com` (2) will map to the app as well.

Now, the regular domain (1) should be handled by the default Laravel routes – what really works well.

The `routes/web.php` (3) looks like that:

```php
Route::get('/', 'ExampleController@index');
```

Now I want a module to handle the subdomain. The app is generally running, the `Modules/SubDomain/Routes/web.php` (4) should look like that (in my opinion and understanding):

```php
Route::group(['domain' => 'subdomain.example.com'], function(){
    Route::get('/', 'SubDomainController@index');
});
```

Now, the problem looks like this: the subdomain is also showing the content of the main domain, the default routes are overriding the module ones. If I place the 3 lines of code out of (4) within (3) in front of the definition above, all works fine. Even if I delete the definition out of (3) and leave that file empty and only the the subdomain config within (4), the subdomain content showing up fine (and the main page shows an 404). Only if I split the routes up like above – like it would be clean coded – it fails.

There are a lot of confusing tips out there – on stackoverflow, Laracast and even here on your GitHub-Issues. But none of them really helps me to fix my problem.

On behalf of @mikemand I also checked `php artisan route:list` – and now THAT is really weird: both times, if I have the configuration like it's really working with the content of (4) prepended to (3) and even if I save the config (3) and (4) like described above, the command gives me the same table both times so it should theoretically work (but doesn't):

```sh
+-----------------------+----------+-----+------+--------------------------------------------------------------+------------+
| Domain                | Method   | URI | Name | Action                                                       | Middleware |
+-----------------------+----------+-----+------+--------------------------------------------------------------+------------+
| subdomain.example.com | GET|HEAD | /   |      | Modules\SubDomain\Http\Controllers\SubDomainController@index | web        |
|                       | GET|HEAD | /   |      | App\Http\Controllers\ExampleController@index                 | web        |
+-----------------------+----------+-----+------+--------------------------------------------------------------+------------+
```

Cheers,
Martin

**Comment by nWidart** [comment] 2018-11-27 21:47
Hello,

This sound very confusing to me. 
You're talking about prepending 4 which is a filename, to 3, which is a file content...

In any case, this sounds more like a general laravel question than anything related to this package.

**Comment by macwinnie** [comment] 2018-11-28 08:04
Hi @nWidart,

it's a problem with your package – since the routes your package register with Laravel are not correctly handled.

And (3) and (4) are both file-contents, not file-names ...

Thanks for investigating and reopening!
Cheers

**Comment by nWidart** [comment] 2018-11-28 08:38
I don't see how it can be an issue with the package. 

The package doesn't do anything with your routes.

What do you mean by "not correctly handled"?

I've used subdomains before with modules, I know others who have too, and never was there an issue. 

Here's a nice quote for you:

> Do not blame the language or libraries. And, never assume that the language is broken, because probability is always against you. 99 percent of the time, the bug is in something you coded.

**Comment by macwinnie** [comment] 2018-11-28 10:18
Thanks for your quote ...

I created the minimal example, I promised. The problem is showing up there as described above. You can find the repository with the minimal example here: https://github.com/macwinnie/laravel-modules-issue_670

What I've done is not coding anything – it's just configuring along the documentation. The one of your add-on and the one of Laravel itself.

Your add-on does somehow register the routes. And I think there is somehow a bug. Please investigate some time and don't block the discussion as above.

Cheers.

**Comment by nWidart** [comment] 2018-11-28 10:21
Sorry I wasn't saying it's never the package's fault, just that it's mostly the case based on the submitted issues.

Sadly I will not have time to debug your issue in the near future. If you find what's wrong exactly please do let us know or submit a PR.

**Comment by kamov** [comment] 2018-12-03 09:12
@macwinnie  I think that the problem is how you define route with subdomain.

I confirm that this have issue also for me:

```php
Route::group(['domain' => env('APP_2URL')], function(){
    Route::get('', function () {
        return view('subdomain');
    })->name('subdomain-view');
});
```

But this work fine for me:


```php
Route::domain(env('APP_2URL'))->group(function () {
    Route::get('/', function () {
   
   		die('i was here');

    });
});
```

This last example is also how laravel docs explain it.

**Comment by kamov** [comment] 2018-12-03 19:14
Yes you are right. It not work correctly.

However, I notice that it not work only for first url "/". But work fine for example with any other url.

For example this not work (this are routes in module SubDomain and on left is first page of subdomain):

![screenshot from 2018-12-03 20-08-03](https://user-images.githubusercontent.com/2345000/49395646-608e4a80-f737-11e8-9726-0c9af1d6da08.png)

While this is the second url of subdomain with "/cc" on url and work fine, you see the view of module:

![screenshot from 2018-12-03 20-07-49](https://user-images.githubusercontent.com/2345000/49395703-887dae00-f737-11e8-8324-0ad61727aa18.png)


I never play with this before, but I will need to use subdomains soon in my project, so I was curious to check into. 

As @nWidart said routes are handled by laravel and not by this package, so this issue could be somewhere in laravel.

Checking php artisan route:list all seem correct, this is result:

![screenshot from 2018-12-03 20-12-43](https://user-images.githubusercontent.com/2345000/49395848-e6aa9100-f737-11e8-8739-c9bced98c8f8.png)

Need to check into more.

**Comment by ercanertan** [comment] 2018-12-05 09:53
I believe if you are using this package then there is no need to use Laravel default routing anymore.
Instead why not create another module to manage main site and give order number 1 and then create subdomain module and give order number 0. So this way you have full control which one is loading first.

**Comment by nWidart** [comment] 2019-03-06 13:05
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Closed by nWidart** 2019-03-06 13:05 UTC

**Comment by GoodM4ven** [comment] 2022-05-09 11:17
Having a separate module for the main view might not be necessary! Check out [this](https://github.com/nWidart/laravel-modules/issues/457#issuecomment-1120964301) comment.
