### ISSUE TITLE
register service providers in register()

### ISSUE THREAD

**Issue by getriebesand** [nWidart/laravel-modules#563] opened 2018-06-25 12:20 UTC
In LaravelModulesServiceProvider  $this->registerModules() should be called in register() like in LumenModulesServiceProvider.

I'm registering a modified translator in my core module. A third party package (e.G. Carbon) needs the translator in its boot method of its service provider. 
But at this time the translator is not registered because  the LaravelModulesServiceProvider register my service provider in it`s boot method and the register method of my service provider will be calles in boot process, not in register process.

there is a merge request which will fix this. (https://github.com/nWidart/laravel-modules/pull/200)
I have extend the LaravelModulesServiceProvider by myself and fixed that. 
But I think thats a laravel lifecycle breaking bug and should be fixed.

**Comment by nWidart** [comment] 2018-06-25 12:21
Hello,

I saw you comment on the PR no need to post everywhere 😄 
The PR explains in details why this can't be done at this time.

**Comment by getriebesand** [comment] 2018-06-25 12:32
Sorry...doesn't know if my comment in PR will be noticed.

because of Asgard right? maybe you can fix this in Asgard soon. Your module package is very cool and useful and in the meantime I will life with my bugfix... :)

**Comment by nWidart** [comment] 2018-06-25 12:37
No worries.

Indeed, I haven't found the cause yet in Asgard.

**Comment by nWidart** [comment] 2018-06-27 16:30
I'll close this for now.

**Closed by nWidart** 2018-06-27 16:30 UTC
