### ISSUE TITLE
Create a module:make-resource [name] [module] command

### ISSUE THREAD

**Issue by Kyslik** [nWidart/laravel-modules#346] opened 2017-09-24 18:12 UTC
I know I can open PR.

Relevant documentation https://laravel.com/docs/5.5/eloquent-resources

**Comment by nWidart** [comment] 2017-09-24 20:01
duplicate of #320

**Closed by nWidart** 2017-09-24 20:01 UTC

**Comment by Kyslik** [comment] 2017-09-24 20:05
Didn't see that one, sorry!

**Comment by nWidart** [comment] 2017-09-24 20:05
No worries 😄
