### ISSUE TITLE
  Type error: Argument 1 passed to Nwidart\Modules\Commands\SeedCommand::reportException() 

### ISSUE THREAD

**Issue by karneaud** [nWidart/laravel-modules#471] opened 2018-01-31 17:57 UTC
I'm running ASGARDCMS 3.4 and using Laravel Framework 5.5.31 with PHP >= 7

I n trying to run the command `php artisan module:seed {modulename}` I get the subject error

>    Type error: Argument 1 passed to Nwidart\Modules\Commands\SeedCommand::reportException() must be an instance of Exception, instance of Error given, called in /home/vagrant/Code/dohlapse/vendor/nwidart/laravel-modules/src/Commands/SeedCommand.php on line 50

**Comment by nWidart** [comment] 2018-02-02 08:29
Thanks for reporting the issue, this is a duplicate of #465

**Closed by nWidart** 2018-02-02 08:29 UTC
