### ISSUE TITLE
Laravel 8 factory doesn't work.

### ISSUE THREAD

**Issue by shankhadevpadam** [nWidart/laravel-modules#1114] opened 2020-11-03 07:17 UTC
In laravel version 8 the factory is not working.

**Comment by nWidart** [comment] 2020-11-03 08:55
duplicate of #1112

**Closed by nWidart** 2020-11-03 08:55 UTC

**Comment by shankhadevpadam** [comment] 2020-11-14 15:50
Still not working. Even I follow all processes.

```
PHP Error:  Class 'Database/Factories/Modules/Post/Entities/PostFactory' not found in /home/padam/html/laravel_projects/laranews/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php on line 670
```
