### ISSUE TITLE
Error installing Modules on a fresh Laravel 6.0

### ISSUE THREAD

**Issue by ahlechandre** [nWidart/laravel-modules#839] opened 2019-09-23 21:39 UTC
**Problem**

Couldn't use *laravel-modules* in most recent Laravel version (6.0). Error given in `Nwidart\Modules\Json::__construct()`.

**Steps to produce**

1. Create a new Laravel 6.0 project:

```bash
$ laravel new project && cd project
```

2. Install laravel-modules:

```bash
$ composer require nwidart/laravel-modules
```

3. Publish modules:

```bash
$ php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"
```

4. Add to autoload:
```json
{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "Modules/"
    }
  }
}
```

5. Access any route: 

```
Symfony\Component\Debug\Exception\FatalThrowableError
Argument 2 passed to Nwidart\Modules\Json::__construct() must be an instance of Illuminate\Filesystem\Filesystem or null, instance of Illuminate\Translation\Translator given, called in /php/softsul-crm-web/vendor/nwidart/laravel-modules/src/Module.php on line 227
```

**Comment by nWidart** [comment] 2019-09-30 08:46
Hi,

Weird, I can't reproduce this. Can you provide an example project (github or zip) where you have this issue?

**Comment by nWidart** [comment] 2019-10-15 11:14
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Closed by nWidart** 2019-10-15 11:14 UTC

**Comment by LoganTFox** [comment] 2020-02-14 17:13
I am having the same issue. Everything was working fine but when I upgraded to Laravel 6 the modules don't register.

**Comment by nWidart** [comment] 2020-02-14 18:15
Did you run the migrate command?

**Comment by LoganTFox** [comment] 2020-02-14 18:16
Fixed. we ran `php artisan module:v6:migrate`

**Comment by zoxed** [comment] 2021-04-01 09:34
Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Modules\Auth\Providers\AuthServiceProvider' not found

  at C:\Users\DELL\Desktop\Laravel\blog6\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:208
    204|      * @return \Illuminate\Support\ServiceProvider
    205|      */
    206|     public function createProvider($provider)
    207|     {
  > 208|         return new $provider($this->app);
    209|     }
    210| }
    211| 

  Exception trace:

  1   Illuminate\Foundation\ProviderRepository::createProvider("Modules\Auth\Providers\AuthServiceProvider")
      C:\Users\DELL\Desktop\Laravel\blog6\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:144
  2   Illuminate\Foundation\ProviderRepository::compileManifest()
      C:\Users\DELL\Desktop\Laravel\blog6\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:61

  Please use the argument -v to see more details.

**Comment by zoxed** [comment] 2021-04-01 09:37
can someone know what i should do, i just did this :
 1 - composer require nwidart/laravel-modules
2 - php artisan module:make Blog User Auth
3- php artisan
and hop i see this error the one above before this comment

**Comment by hadjamagamy** [comment] 2024-08-10 23:56
I hope you are well I initialized a new Laravel 11 project with inertia React, Breeze and Widart for a modular application I created my Auth module and I have this error PS C:\Users\MagamyGBANEADJA\OneDrive - FINACTU INTERNATIONAL\Office\example-modular-app> php artisan serve

   Error 

  Class "Modules\Auth\Providers\AuthServiceProvider" not found

  in supplier\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:206
    202▕ * @return \Illuminate\Support\ServiceProvider
    203▕ */
    204▕ public function createProvider($provider)
    205▕ {
  ➜ 206▕ returns the new $provider($this->app);
    207▕ }
    208▕ }
    209▕

  1 provider\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:142
      Illuminate\Foundation\ProviderRepository::createProvider("Modules\Auth\Providers\AuthServiceProvider")   

  2 provider\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:61
      Illuminate\Foundation\ProviderRepository::compileManifest()
