### ISSUE TITLE
--database didn't use in migrate-xxxx(xxxx: rollback\reset\refresh)

### ISSUE THREAD

**Issue by HuNanZai** [nWidart/laravel-modules#87] opened 2016-11-10 08:57 UTC
i look step by step into your code and i found this problem:

the problem is that you didn't use the '--database' option in your Migrations/Migrator.php's
`function table()` that will cause a lookup in the default db connection not the specific one i want.

as a advice, i think it's necessary add some method like `setConnection()` in the Migrator Class and use it in the command.

**Comment by nWidart** [comment] 2016-11-10 09:27
Hello,

This is a duplicate of #49. Thanks for the tip though, feel free to submit a PR if you feel like it.

**Comment by nWidart** [comment] 2016-11-23 10:40
This was fixed by pull request #88 
Let me know if it fixes your problem.

**Comment by HuNanZai** [comment] 2016-11-25 15:30
haha~ it fixes my condition, hope it helps the other people!

**Comment by nWidart** [comment] 2017-01-12 16:55
Fixed in 1.15.0

**Closed by nWidart** 2017-01-12 16:55 UTC
