### ISSUE TITLE
How to use json translation files using modules? (Translation Strings As Keys)

### ISSUE THREAD

**Issue by dexcell** [nWidart/laravel-modules#954] opened 2020-04-01 16:22 UTC
I want to use translation strings as key, how to do it in laravel modules?
https://laravel.com/docs/6.x/localization#using-translation-strings-as-keys

I've tried adding the json file to modules lang folder. e.g. `Modules\ModuleName\Resources\lang\id.json` but laravel doesn't read it.

Does laravel modules support Translation Strings As Keys? (Not short key translation).

Thanks

**Comment by JamesHemery** [comment] 2020-04-04 00:22
Hi @dexcell,

This package can help you => [laravel-json-translation-loader](https://github.com/JamesHemery/laravel-json-translation-loader)

**Comment by dexcell** [comment] 2020-04-04 02:28
@JamesHemery 
Thank you! i will have a look at it

**Comment by nWidart** [comment] 2020-04-13 17:11
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by dexcell** [comment] 2020-04-14 07:18
Unfortunately there is still no solution for this.

**Comment by nWidart** [comment] 2020-04-14 09:25
This is not related to this package as far as I can see. Users can choose to do this however they prefer.

**Comment by dexcell** [comment] 2020-04-17 07:27
Hi thank you for the reply,

I'm sorry i have to a bit disagree, i think laravel modules should support default laravel translation out of the box. 

Since default laravel offers translation strings as keys, then i want to use it inside the modules just like normal laravel app. (isn't that the purpose of laravel modules?).

For now i managed to load the json translation manually by adding `loadJsonTranslationsFrom` inside `registerTranslation` function in service provider file.
I hope the generator would done this automatically (e.g `php artisan module:make ModuleName`)
````
/**
     * Register translations.
     *
     * @return void
     */
    public function registerTranslations()
    {
        $langPath = resource_path('lang/modules/modulename');

        if (is_dir($langPath)) {
            $this->loadTranslationsFrom($langPath, 'modulename');
            $this->loadJsonTranslationsFrom($langPath);
        } else {
            $this->loadTranslationsFrom(module_path('ModuleName', 'Resources/lang'), 'modulename');
            $this->loadJsonTranslationsFrom(module_path('ModuleName', 'Resources/lang'));
        }
    }
````

**Comment by nWidart** [comment] 2020-04-17 07:29
This package supports laravel translations out of the box. Both json and the PHP array way.

**Comment by dexcell** [comment] 2020-04-17 07:33
Unfortunately on my test it doesn't load the json translation file, only the PHP array way. 
(On laravel v6) i haven't tried the v7 yet.

After i added `loadJsonTranslationsFrom` then it does read the json file correctly.
Looks like `loadTranslationsFrom` only load php array translation.

**Comment by dexcell** [comment] 2020-04-17 07:37
Sorry, i mean json translation file without prefixing.

**Comment by l1th1um** [comment] 2020-08-10 08:21
I use this 

$this->loadJsonTranslationsFrom(__DIR__.'/../Resources/Lang');

**Comment by usmanabbas2211** [comment] 2020-11-21 11:25
hey

**Comment by raulpacheco2k** [comment] 2021-06-27 20:32
> Hi thank you for the reply,
> 
> I'm sorry i have to a bit disagree, i think laravel modules should support default laravel translation out of the box.
> 
> Since default laravel offers translation strings as keys, then i want to use it inside the modules just like normal laravel app. (isn't that the purpose of laravel modules?).
> 
> For now i managed to load the json translation manually by adding `loadJsonTranslationsFrom` inside `registerTranslation` function in service provider file.
> I hope the generator would done this automatically (e.g `php artisan module:make ModuleName`)
> 
> ```
> /**
>      * Register translations.
>      *
>      * @return void
>      */
>     public function registerTranslations()
>     {
>         $langPath = resource_path('lang/modules/modulename');
> 
>         if (is_dir($langPath)) {
>             $this->loadTranslationsFrom($langPath, 'modulename');
>             $this->loadJsonTranslationsFrom($langPath);
>         } else {
>             $this->loadTranslationsFrom(module_path('ModuleName', 'Resources/lang'), 'modulename');
>             $this->loadJsonTranslationsFrom(module_path('ModuleName', 'Resources/lang'));
>         }
>     }
> ```

Thanks! This solution helped me! I believe this library should implement this solution, it is a flawed view to think that it should not be implemented.

**Comment by bedoya** [comment] 2021-08-24 22:12
> This package supports laravel translations out of the box. Both json and the PHP array way.

Wouldn't it be nice if your answer was not always limited to state the fact that your packages can do stuff, but to guide others who care enough to give a try to your work? You state that your package supports json translations out of the box, but you don't care to show how we should do it, because you assume that if we idiots don't know how to do it we shouldn't even be using your package, right? WRONG! ... have a little modesty and get down to earth with mortals.

**Comment by raulpacheco2k** [comment] 2021-08-24 22:55
@bedoya Congratulations on your reply. I agree with you.

**Comment by tuaititecnologia** [comment] 2021-11-19 13:24
Nowdays still does not work out of the box as mentioned before. At least is not documented. 
This is the registerTranslations() not using hardcoded module name, so it's easier to copy and paste. 

`   
public function registerTranslations()
    {
        $langPath = resource_path('lang/modules/' . $this->moduleNameLower);

        if (is_dir($langPath)) {
            $this->loadTranslationsFrom($langPath, $this->moduleNameLower);
            $this->loadJsonTranslationsFrom($langPath);
        } else {
            $this->loadTranslationsFrom(module_path($this->moduleName, 'Resources/lang'), $this->moduleNameLower);
            $this->loadJsonTranslationsFrom(module_path($this->moduleName, 'Resources/lang'));
        }
    }
`

**Comment by raulpacheco2k** [comment] 2021-11-19 14:01
> O Nowdays ainda não funciona fora da caixa, como mencionado antes. Pelo menos não está documentado. Este é o registerTranslations () que não usa o nome do módulo codificado, então é mais fácil de copiar e colar.
> 
> ```
> public  function  registerTranslations ()
>     {
>         $ langPath = resource_path ( 'lang / modules /' . $ this -> moduleNameLower );
>         if ( is_dir ( $ langPath )) {
>              $ this -> loadTranslationsFrom ( $ langPath , $ this -> moduleNameLower );
>             $ this -> loadJsonTranslationsFrom ( $ langPath );
>         } else {
>              $ this -> loadTranslationsFrom ( module_path ( $ this -> moduleName , 'Resources / lang' ), $ this -> moduleNameLower );
>             $ Presente -> loadJsonTranslationsFrom ( module_path ( $ presente -> moduleName , 'Resources / lang' ));
>         }
>     }
> ```

In my tests this works on Laravel 8.

**Comment by raulpacheco2k** [comment] 2021-11-19 14:02
> Nowdays still does not work out of the box as mentioned before. At least is not documented. This is the registerTranslations() not using hardcoded module name, so it's easier to copy and paste.
> 
> ```
> public function registerTranslations()
>     {
>         $langPath = resource_path('lang/modules/' . $this->moduleNameLower);
>         if (is_dir($langPath)) {
>             $this->loadTranslationsFrom($langPath, $this->moduleNameLower);
>             $this->loadJsonTranslationsFrom($langPath);
>         } else {
>             $this->loadTranslationsFrom(module_path($this->moduleName, 'Resources/lang'), $this->moduleNameLower);
>             $this->loadJsonTranslationsFrom(module_path($this->moduleName, 'Resources/lang'));
>         }
>     }
> ```

In my tests this works on Laravel 8.

**Comment by Marciobds** [comment] 2021-11-25 16:27
I'm having some trouble with this as well, but for me only the translations from the first module loaded are being actually loaded, translations from all other modules are not.

I can't find a way of making it work.

**Comment by limsocheat** [comment] 2022-02-17 03:55
> Nowdays still does not work out of the box as mentioned before. At least is not documented. This is the registerTranslations() not using hardcoded module name, so it's easier to copy and paste.
> 
> ```
> public function registerTranslations()
>     {
>         $langPath = resource_path('lang/modules/' . $this->moduleNameLower);
>         if (is_dir($langPath)) {
>             $this->loadTranslationsFrom($langPath, $this->moduleNameLower);
>             $this->loadJsonTranslationsFrom($langPath);
>         } else {
>             $this->loadTranslationsFrom(module_path($this->moduleName, 'Resources/lang'), $this->moduleNameLower);
>             $this->loadJsonTranslationsFrom(module_path($this->moduleName, 'Resources/lang'));
>         }
>     }
> ```

**I followed your instruction, but translation is not loaded. It return raw string instead.** 
`{{  __('reservation:Reservation Confirmed') }}`

**return** 
reservation:Reservation Confirmed

**my ReservationServiceProvider:** 

```
/**
     * Register translations.
     *
     * @return void
     */
    public function registerTranslations()
    {
        $langPath = resource_path('lang/modules/' . $this->moduleNameLower);

        if (is_dir($langPath)) {
            $this->loadTranslationsFrom($langPath, $this->moduleNameLower);
            $this->loadJsonTranslationsFrom($langPath);
        } else {
            $this->loadTranslationsFrom(module_path($this->moduleName, 'resources/lang'), $this->moduleNameLower);
            $this->loadJsonTranslationsFrom(module_path($this->moduleName, 'resources/lang'));
        }
    }
```

**Comment by dcblogdev** [comment] 2022-02-17 13:16
I'll re-open this so I can look into this further.

**Comment by dcblogdev** [comment] 2022-02-18 11:41
it works for me, enabled both json and traditional files:

```php
public function registerTranslations()
    {
        $langPath = resource_path('lang/modules/' . $this->moduleNameLower);

        if (is_dir($langPath)) {
            $this->loadTranslationsFrom($langPath, $this->moduleNameLower);
            $this->loadJsonTranslationsFrom($langPath, $this->moduleNameLower);
        } else {
            $this->loadTranslationsFrom(module_path($this->moduleName, 'Resources/lang'), $this->moduleNameLower);
            $this->loadJsonTranslationsFrom(module_path($this->moduleName, 'Resources/lang'), $this->moduleNameLower);
        }
    }
 ```
 
 Changing my language in config to fr

```php
'locale' => 'fr',
```

then in a module create a fr.json file:

```php
{
  "Name ok": "changed",
}
```

In a view:

```php
{{ __('Name ok') }}
```

shows `changed` for me.

When using json translations you can only prefix the key if you manually add a prefix such as:

```php
{
  "reservation:Name ok": "changed",
}
```

In a view:

```php
{{ __('reservation:Name ok') }}
```

This will be due to Laravel will be looking for an exact match.

**Closed** 2022-02-19 19:10 UTC

**Comment by limsocheat** [comment] 2022-03-30 09:58
> it works for me, enabled both json and traditional files:
> 
> ```
> public function registerTranslations()
>     {
>         $langPath = resource_path('lang/modules/' . $this->moduleNameLower);
> 
>         if (is_dir($langPath)) {
>             $this->loadTranslationsFrom($langPath, $this->moduleNameLower);
>             $this->loadJsonTranslationsFrom($langPath, $this->moduleNameLower);
>         } else {
>             $this->loadTranslationsFrom(module_path($this->moduleName, 'Resources/lang'), $this->moduleNameLower);
>             $this->loadJsonTranslationsFrom(module_path($this->moduleName, 'Resources/lang'), $this->moduleNameLower);
>         }
>     }
> ```
> 
> Changing my language in config to fr
> 
> ```
> 'locale' => 'fr',
> ```
> 
> then in a module create a fr.json file:
> 
> ```
> {
>   "Name ok": "changed",
> }
> ```
> 
> In a view:
> 
> ```
> {{ __('Name ok') }}
> ```
> 
> shows `changed` for me.
> 
> When using json translations you can only prefix the key if you manually add a prefix such as:
> 
> ```
> {
>   "reservation:Name ok": "changed",
> }
> ```
> 
> In a view:
> 
> ```
> {{ __('reservation:Name ok') }}
> ```
> 
> This will be due to Laravel will be looking for an exact match.

I followed all of your code, but still not working: 

**1. service provider** 
<img width="1163" alt="Screen Shot 2022-03-30 at 4 55 39 PM" src="https://user-images.githubusercontent.com/6656644/160804823-6b22bae5-6e08-4e9c-bf63-27ede0d60a23.png">

**2. km.json** 
<img width="492" alt="Screen Shot 2022-03-30 at 4 56 05 PM" src="https://user-images.githubusercontent.com/6656644/160804911-f9e9df78-ac9f-48f0-be9d-a4c8b7cb20a0.png">

**3. blade** 
<img width="986" alt="Screen Shot 2022-03-30 at 4 56 31 PM" src="https://user-images.githubusercontent.com/6656644/160805008-f9916dae-972f-4366-8697-a3d62f93e513.png">

**4. result**
<img width="511" alt="Screen Shot 2022-03-30 at 4 56 52 PM" src="https://user-images.githubusercontent.com/6656644/160805115-2286b4f1-916d-4be3-9590-ce1c951bbd7c.png">

I also tried: {{ __('academic:Academic') }}, {{ __('academic::Academic') }}, {{ __('Academic') }} in blade, but still not render. 

Laravel Version: "laravel/framework": "^9.0",
Module Version: "nwidart/laravel-modules": "^9.0",
docs: https://docs.laravelmodules.com/v9/languages

**Comment by nyneplus** [comment] 2022-04-07 09:47
I am upgrading to Laravel 9 and experience the same as @limsocheat. I will try to find to root cause or is any found already?

**Comment by vietsach0808** [comment] 2022-04-13 04:41
I have found a solution to this problem. Open file: /config/app.php and change
```
'locale' => '',
'fallback_locale' => '',
```
Create the Locale middleware and set the locale you want.
```
public function handle($request, Closure $next)
    {
        $locale = 'en';
        \App::setLocale($locale);
        return $next($request);
    }
```
Add this middleware to your routes.
After it the translation will work.
```
Route::group(['middleware' => 'locale'], function() {
// your route
});
```

**Comment by nyneplus** [comment] 2022-05-09 13:23
> 

So basically the locale is not set?  Adding middelware is a workaround but not really a nice one. Is it possible to fix it somehow in de package?

**Comment by nyneplus** [comment] 2022-05-10 15:20
For me it was the component [BenSampo/laravel-enum](https://github.com/BenSampo/laravel-enum). It loaded a translation too soon. 
I found it by  adding 
`debug_print_backtrace();exit();`

to
`Illuminate\Foundation\Helpers.php` 
@line 882 in the function __($key = null, $replace = [], $locale = null) so i saw where it was used to soon.

**Comment by Rattone** [comment] 2022-10-03 14:10
> > it works for me, enabled both json and traditional files:
> > ```
> > public function registerTranslations()
> >     {
> >         $langPath = resource_path('lang/modules/' . $this->moduleNameLower);
> > 
> >         if (is_dir($langPath)) {
> >             $this->loadTranslationsFrom($langPath, $this->moduleNameLower);
> >             $this->loadJsonTranslationsFrom($langPath, $this->moduleNameLower);
> >         } else {
> >             $this->loadTranslationsFrom(module_path($this->moduleName, 'Resources/lang'), $this->moduleNameLower);
> >             $this->loadJsonTranslationsFrom(module_path($this->moduleName, 'Resources/lang'), $this->moduleNameLower);
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Changing my language in config to fr
> > ```
> > 'locale' => 'fr',
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then in a module create a fr.json file:
> > ```
> > {
> >   "Name ok": "changed",
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In a view:
> > ```
> > {{ __('Name ok') }}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > shows `changed` for me.
> > When using json translations you can only prefix the key if you manually add a prefix such as:
> > ```
> > {
> >   "reservation:Name ok": "changed",
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In a view:
> > ```
> > {{ __('reservation:Name ok') }}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will be due to Laravel will be looking for an exact match.
> 
> I followed all of your code, but still not working:
> 
> **1. service provider** <img alt="Screen Shot 2022-03-30 at 4 55 39 PM" width="1163" src="https://user-images.githubusercontent.com/6656644/160804823-6b22bae5-6e08-4e9c-bf63-27ede0d60a23.png">
> 
> **2. km.json** <img alt="Screen Shot 2022-03-30 at 4 56 05 PM" width="492" src="https://user-images.githubusercontent.com/6656644/160804911-f9e9df78-ac9f-48f0-be9d-a4c8b7cb20a0.png">
> 
> **3. blade** <img alt="Screen Shot 2022-03-30 at 4 56 31 PM" width="986" src="https://user-images.githubusercontent.com/6656644/160805008-f9916dae-972f-4366-8697-a3d62f93e513.png">
> 
> **4. result** <img alt="Screen Shot 2022-03-30 at 4 56 52 PM" width="511" src="https://user-images.githubusercontent.com/6656644/160805115-2286b4f1-916d-4be3-9590-ce1c951bbd7c.png">
> 
> I also tried: {{ __('academic:Academic') }}, {{ __('academic::Academic') }}, {{ __('Academic') }} in blade, but still not render.
> 
> Laravel Version: "laravel/framework": "^9.0", Module Version: "nwidart/laravel-modules": "^9.0", docs: https://docs.laravelmodules.com/v9/languages

I have the same problem in a Laravel 8 installation, performing the same steps indicated by @dcblogdev and @limsocheat the translations are not read, keep getting the translations from project root (not module).

...beyond this, am I wrong or the loadJsonTranslationsFrom() method just want one parameter?

https://laravel.com/api/9.x/Illuminate/Support/ServiceProvider.html#method_loadJsonTranslationsFrom

**Comment by shawe** [comment] 2024-03-19 08:58
![image](https://github.com/nWidart/laravel-modules/assets/145989/20c8c969-7f99-4a72-b114-252992ac0686)

For me, the problem with the translations are only the routes used, by default is not using the same standard path that in laravel projects. Also, for me, it may include the original array translation folder in the root module folder.

- Modules/YourModule/lang/XX/YYYY.php (pending implementation)
- Modules/YourModule/resources/lang/XX.json (solved with the minor change in the screenshot)

By default in laravel-modules it's using a combined path that is not based on the original laravel structure for languages:
- Modules/YourModule/lang/XX.json

At this moment, for me is enough only with json file to get all translations in one file, but I think that is always preferable get it in the common way in the Laravel to get full compatibility on implement it has any dev prefers to use on each case.

**Comment by alpemreelmas** [comment] 2024-08-01 17:32
> ![image](https://private-user-images.githubusercontent.com/145989/313984756-20c8c969-7f99-4a72-b114-252992ac0686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzI4NzgsIm5iZiI6MTcyMjUzMjU3OCwicGF0aCI6Ii8xNDU5ODkvMzEzOTg0NzU2LTIwYzhjOTY5LTdmOTktNGE3Mi1iMTE0LTI1Mjk5MmFjMDY4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxNzE2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTMyN2Y0NjM0N2ZlY2QwYWQ0MmY5ODllODhmZmY2NmQyYTkzZjM0MzE1ZThhODAyNDZkYTk1YmU0NGExNTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rlislkg1KxQXEC0A4rIChSaYYVD3X63t4l8D_aKgrgQ)
> 
> For me, the problem with the translations are only the path used, by default is not using the same standard path that in laravel projects. Also, for me, it may include the original array translation folder in the root module folder (not in core project as lang/modules, the lang/XX/YYYY.php inside the module).
> 
> * Modules/YourModule/lang/XX/YYYY.php (pending implementation)
> * Modules/YourModule/resources/lang/XX.json (solved with the minor change in the screenshot)
> 
> By default in laravel-modules it's using a combined path that is not based on the original laravel structure for languages:
> 
> * Modules/YourModule/lang/XX.json
> 
> At this moment, for me is enough only with json file to get all translations in one file, but I think that is always preferable get it in the common way in the Laravel to get full compatibility on implement it has any dev prefers to use on each case.

I'm not sure if I use it correct with helper functions to call translation can you also share usage of it. 
For example: trans("user::errors.not_found") or trans("errors.not_found")
