### ISSUE TITLE
Laravel  5.8.29 has isuue with helper function  module_path('Blog');

### ISSUE THREAD

**Issue by madhankd** [nWidart/laravel-modules#803] opened 2019-08-08 04:04 UTC
The error is :

 Call to a member function getPath() on null

  at C:\wamp64\www\nfp\vendor\nwidart\laravel-modules\src\helpers.php:8
     4|    function module_path($name)
     5|     {
     6|         $module = app('modules')->find($name);
     7|
     8|         return $module->getPath();
     9|     }
    10| }
    11|
    12| if (! function_exists('config_path')) {

**Comment by nWidart** [comment] 2019-08-19 08:47
That seems strange, is the service provider from laravel-modules registered?

**Comment by nWidart** [comment] 2019-09-02 17:52
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Closed by nWidart** 2019-09-02 17:52 UTC

**Comment by tomhatzer** [comment] 2020-07-14 15:14
@nWidart just a quick update to this issue.

This error happens when you are moving your packages into separate composer packages and push them to eg. github.
When you try loading the module and don't have `"type": "laravel-module"` set in your composer.json and have not installed the package `joshbrw/laravel-module-installer` you'll get the error from above. This error is caused by the Service Provider autoloading somehow that loads module stuff too early or something like that.

If you do everything like described in the [Publishing modules section](https://nwidart.com/laravel-modules/v6/advanced-tools/publishing-modules), you'll be able to successfully install all the modules without the error from above.

**Comment by nWidart** [comment] 2020-07-14 16:39
Weird, I don't use that package in asgardcms and it works.

What you say makes me think of something different though, you could try to require the laravel/support or wherever the laravel service provider setup is, as well as checking where the `app()` function is defined.
