### ISSUE TITLE
Routes defined in routes/web.php not working anymore

### ISSUE THREAD

**Issue by amitshahc** [nWidart/laravel-modules#755] opened 2019-05-09 05:53 UTC
Below routes defined in Laravel's default routing file `routes/web.php` are not working from the browser, but can be seen in `route:list`.

The same block of code defined in any `routes.php` under any module is working fine. 

```
Route::group(['prefix' => 'api', 'namespace' => 'App\Http\Controllers'], function () {
    Route::get('/world/countries', 'API\WorldController@countrylist')->name('API.world.countrylist');
    Route::get('/world/regions', 'API\WorldController@regionlist')->name('API.world.regionlist');
    Route::get('/world/cities', 'API\WorldController@citylist')->name('API.world.citylist');
});
```

**Comment by nWidart** [comment] 2019-05-09 06:45
Hi,

Is your file loaded? Do you see it in the modules.json file un the `files` key?
In newer versions of this package, routes are now written in a "route service provider", instead of that raw php file.

**Comment by amitshahc** [comment] 2019-05-09 10:13
> 
> 
> Hi,
> 
> Is your file loaded? Do you see it in the modules.json file un the `files` key?
> In newer versions of this package, routes are now written in a "route service provider", instead of that raw php file.

which file are you talking about? `routes/web.php` is the laravel default file. and my concern is about that only. all route.php under any module is working fine. my Laravel v is 5.5.44 and nwidart/module v 3.3

**Comment by nWidart** [comment] 2019-05-09 11:03
the file i mention: `modules.json`

**Comment by nWidart** [comment] 2019-05-09 11:04
Oh I see, you're saying "global" routes aren't registering? Not sure in that case, I 'd check if they're properly loaded etc.

**Comment by amitshahc** [comment] 2019-05-10 11:55
> 
> 
> Oh I see, you're saying "global" routes aren't registering? Not sure in that case, I 'd check if they're properly loaded etc.

How should i check it? just by echo?
The routes defined in web.php are there in #php artisan route:list

**Comment by nWidart** [comment] 2019-05-10 12:07
However you prefer debugging code. Echo, dd, breakpoints, etc.

**Comment by amitshahc** [comment] 2019-05-10 12:20
I dd it and the web.php is loading perfectly fine. but still the same block of Route::group() code working under the route.php (inside any Module). but not from laravel's default /routes/web.php

**Comment by nWidart** [comment] 2019-05-10 12:30
I tried to reproduce this here: https://github.com/nWidart/modules-routes-tests
But unable to reproduce the error you have.

**Comment by amitshahc** [comment] 2019-05-10 12:49
I found why this issue occuring. but got another issue now.

This was occurring in my case because i had defined a wildcard kind of routes for search urls in `Modules\m1\http\routes.php`
```
// Search
Route::group(['middleware' => 'web', 'namespace' => 'Modules\Website\Http\Controllers'], function () {
    Route::post('/', 'ShopList\ShoplistController@search')->name('search.post.home');
    Route::get('/{address_1}/{address_2?}/{address_3?}/{address_4?}', 'ShopList\ShoplistController@shoplist')->name('search.get');
    Route::post('/{address_1}/{address_2?}/{address_3?}/{address_4?}', 'ShopList\ShoplistController@search')->name('search.post.form');
});
```

now as all the routes defined under `routes.php` under any `Modules/..` were taking precedence over the `web.php` routes. the route defined in the `web.php` were not reaching. So now I tried to move this to the `web.php`.

New Issue now:

The namespace attribute is not working as it tries to search the controllers under `App\Http\Controllers\Modules\Website\Http\Controllers\ShopList\ShoplistController` even though I added `\` in front of Modules.

**Comment by nWidart** [comment] 2019-05-10 12:54
aha yea I thought you said routes weren't shown on the `route:list` output.

About your new issue. It is working, I used on many projects including AsgardCMS.

you're not giving any information so hard to help you.

**Comment by amitshahc** [comment] 2019-05-10 16:28
1. Sir, I already started stating that the routes can be seen in route:list if you had read it full.
2. What information i am still not giving to you? about new issue the error is:
App\Http\Controllers\Modules\Website\Http\Controllers\ShopList\ShoplistController not found. so it's apperenty trying to find th

**Comment by nWidart** [comment] 2019-05-10 16:34
Can you reproduce this issue in a code base you can share? Use https://github.com/nWidart/modules-routes-tests for example.

**Comment by amitshahc** [comment] 2019-05-13 04:44
composer install/update throws lots of dependency errors as I have updated the composer.json with:

```
"require": {
        "php": ">=7.0.0",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "^1.0",
        "nwidart/laravel-modules": "^3.3"
```

can you create a laravel project with 5.5 and "nwidart/laravel-modules": "^3.3"

**Comment by nWidart** [comment] 2019-05-13 06:40
that does not make sense, it doesn't stop working like that :D 
Also you're using a very old version.

**Comment by amitshahc** [comment] 2019-05-13 11:03
I think, it doesn't matter what make sense in this case. the truth is it's not working.

```
D:\Installation\Apache24\htdocs\nwidart>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nwidart/laravel-modules 5.0.0 -> satisfiable by nwidart/laravel-modules[5.0.0].
    - nwidart/laravel-modules 5.0.0 requires php >=7.2 -> your PHP version (7.1.17) does not satisfy that requirement.


D:\Installation\Apache24\htdocs\nwidart>
```

I had installed it in last september, 2018. the composer took the best from his side. Upgrading to new version will also prompt me to upgrade PHP and Laravel version. 

Can we try to fix this using the current vertion settings? It must not be very difficult for you to debug the cause.

**Comment by nWidart** [comment] 2019-05-13 11:06
It is working, I provided you the example app which shows this.

It is very difficult to debug. You're using a very old version, which is not supported. So even if there's a big in that version, you won't get a fix anyway.

**Comment by amitshahc** [comment] 2019-05-13 11:39
Ok i will try to reproduce in your repository.

**Comment by nWidart** [comment] 2019-05-31 18:00
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Closed by nWidart** 2019-05-31 18:00 UTC

**Comment by jtomek** [comment] 2019-08-30 08:25
Hi, I'm facing this problem too. One of my Module api.php files suddenly stopped being scanned for routes. I'm not sure why and how to solve it. Once I solve it, I'll let you guys know.

**Comment by marcelogarbin** [comment] 2019-12-08 14:24
I am experiencing something similar, I am trying to get the routes inside the module service provider, and it is returning me as undefined. The strange thing is that some modules work and some don't.

What can I check to see if I can find the beginning of the problem?

**Comment by nWidart** [comment] 2019-12-08 14:48
If some work and some don't, could be inactive modules? Check if all routes are loaded etc.

**Comment by marcelogarbin** [comment] 2019-12-08 15:07
> If some work and some don't, could be inactive modules? Check if all routes are loaded etc.

I deactivated all modules and left only what was in trouble, and then tested what was ok.

Strange this behavior because the modules are identical (except the fact that one has auth), changing the names of course .. maybe I will try to create a new module..

I tried to put auth in the "teste" route but the error occurred..

module: Site
![image](https://user-images.githubusercontent.com/9335588/70391241-b6807880-19b1-11ea-993f-db3849698898.png)

![image](https://user-images.githubusercontent.com/9335588/70391254-d748ce00-19b1-11ea-95f3-264e18dafe2d.png)

![image](https://user-images.githubusercontent.com/9335588/70391336-d6fd0280-19b2-11ea-9560-5443bad05613.png)


module: Dashboard
![image](https://user-images.githubusercontent.com/9335588/70391277-1e36c380-19b2-11ea-86cf-1c5a6be1f14f.png)

![image](https://user-images.githubusercontent.com/9335588/70391290-3b6b9200-19b2-11ea-8572-06111fc24f03.png)

![image](https://user-images.githubusercontent.com/9335588/70391300-53dbac80-19b2-11ea-82ab-7bf9ddfa234a.png)

**Comment by nWidart** [comment] 2019-12-08 15:09
I can only see the reason that you're asking for routes too soon.

**Comment by marcelogarbin** [comment] 2019-12-08 15:34
> I can only see the reason that you're asking for routes too soon.

Please, could you explain?

Why would one module work and the other not? That's what I didn't understand...

**Comment by nWidart** [comment] 2019-12-08 15:35
I can't really find this out either. Modules are loaded in a certain order.

**Comment by marcelogarbin** [comment] 2019-12-08 16:13
I removed and re-created the module with the following routes:

![image](https://user-images.githubusercontent.com/9335588/70392181-ee8cb900-19bb-11ea-9b50-8bdb15c3ae3c.png)

I debug route by route, so some work and some don't..

![image](https://user-images.githubusercontent.com/9335588/70392203-2d227380-19bc-11ea-9a2f-1c323e20ea46.png)


Is there somewhere I can investigate this problem further? this is blocking my development and I need to solve :worried:

**Comment by nWidart** [comment] 2019-12-08 16:17
I already did.

It's likely not all modules are booted yet from where you're debugging.

**Comment by marcelogarbin** [comment] 2019-12-08 16:22
but this is the only active module.. it makes no sense as it does not depend on other modules.. as you can see, some routes of the same module work and some don't.

**Comment by nWidart** [comment] 2019-12-08 16:23
That's weird. No idea why you have that. It's not related to the package though. The package doesnt touch your routes.

**Comment by jamilalidrus** [comment] 2020-01-03 06:30
i am get some error... my route is not found on my module, can you help me?

**Comment by Bluefitdev** [comment] 2020-03-03 03:48
I'm getting the same error.

The route shows in `php artisan route:list`, but when i try to reach the controllers via API it does not work. When I recreated the same route through the `routes/api.php` then it works.

Note: both modules were moved from the previous project, I enabled them, did the auto loading and composer dump-autoload

What else should I do?

Thanks

**Comment by kjostling** [comment] 2020-03-08 16:12
Dunno but have you activated the modules? I had to do that after upgrade from Laravel 5 to 6.

`php artisan module:activate <Module>`

**Comment by nWidart** [comment] 2020-03-08 16:16
@kjostling There's an upgrade command specifically for this purpose. 

```
php artisan module:v6:migrate
```

**Comment by kjostling** [comment] 2020-03-08 16:18
@nWidart 
Ahhh... Thanks. Missed that one :)

**Comment by robertwt7** [comment] 2020-03-08 23:30
in my case i forgot to remove the route `->where('any', '.*');` for my react app. 

Apparently that is overwriting the modules route

**Comment by Mauriinf** [comment] 2020-06-13 01:48
> I removed and re-created the module with the following routes:
> 
> ![image](https://user-images.githubusercontent.com/9335588/70392181-ee8cb900-19bb-11ea-9b50-8bdb15c3ae3c.png)
> 
> I debug route by route, so some work and some don't..
> 
> ![image](https://user-images.githubusercontent.com/9335588/70392203-2d227380-19bc-11ea-9a2f-1c323e20ea46.png)
> 
> Is there somewhere I can investigate this problem further? this is blocking my development and I need to solve


same problem can someone help me

**Comment by Mauriinf** [comment] 2020-06-13 01:57
I cannot access my routes with names that I have created in my module from any view
web.php
Route::get('/Student', 'StudentController@index')->name('profile');
ModuleExample/Resources/views/index.blade.php
<a href="{{ url('profile') }}">Some Text</a>
ERROR
Route [profile] not defined.

**Comment by HashmatWaziri** [comment] 2020-08-11 09:49
> Hello! I also encountered this problem before. Please check your Apache's httpd.conf file. Make sure that you enabled the `LoadModule rewrite_module modules/mod_rewrite.so` by removing the `#` from the start line of the code.
> 
> And also change inside the httpd.conf from Require all denied to Require all granted, AllowOverride All, and Options Indexes FollowSymLinks
> 
> Like This:
> ![Capture](https://user-images.githubusercontent.com/13413228/63312807-2dc3cb00-c335-11e9-827e-86c983773aa9.PNG)
