### ISSUE TITLE
Error in SeedCommand.php

### ISSUE THREAD

**Issue by ebisbal** [nWidart/laravel-modules#579] opened 2018-07-05 12:30 UTC
### Summary of issue
There are errors in file SeedCommand.php

### Steps to reproduce
Build a seeder with errors and try to seed the DB.

### Solution
protected function renderException($output, \Throwable $e)
{
    // $this->laravel[ExceptionHandler::class]->renderForConsole($output, $e);
    $this->laravel[ExceptionHandler::class]->renderForConsole($output, new \Exception($e));
}

protected function reportException(\Throwable $e)
{
    // $this->laravel[ExceptionHandler::class]->report($e);
    $this->laravel[ExceptionHandler::class]->report(new \Exception($e));
}

**Comment by nWidart** [comment] 2018-07-05 12:31
Duplicate of #574 (and others)

The solution you are proposing isn't really clear here.

**Closed by nWidart** 2018-07-05 12:31 UTC
