### ISSUE TITLE
   Nwidart\Modules\Exceptions\InvalidActivatorClass  : You don't have a valid ac tivator configuration class. This might be due to your config being out of date.   Run php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServic eProvider" --force to publish the up to date configuration

### ISSUE THREAD

**Issue by vahnmarty** [nWidart/laravel-modules#928] opened 2020-02-26 08:51 UTC
![image](https://user-images.githubusercontent.com/8845438/75325953-bad37800-58b4-11ea-8a28-91a7bf753147.png)

I have used 
> php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServicePr ovider"
> -- force

but still I got the error. weird.

**Comment by nWidart** [comment] 2020-02-26 21:00
Hi,

Did you check if you have the `FileActivator` class available?

**Comment by rowasc** [comment] 2020-04-05 05:59
hey thanks so much for this library @nWidart . It's great and it (99% of the time) just makes handling modules much more streamlined and easy. 

I just thought I'd ping here to follow up since this happens to me as well. 
The way to reproduce it is (at least for me)
- Have a working branch *without* nwidart/laravel-modules   (let's call it `master`)
- Switch to a new branch (let's call it `modules`) , install nwidart/laravel-modules , do the config, work happily for hours. It just works.
Now in another place, maybe your remote server, you have been deploying `master` until this point
- Checkout your new branch `modules`
- Run `composer install`
boom, it will explode in the way the original poster described. 

The way I was able to "fix" this was basically switching to my `master` branch again, which did not have nwidart/laravel-modules, then running `composer require nwidart/laravel-modules` in there , then running `php artisan config:cache`  , then switching again to `modules`  and running composer install etc...

**Comment by nWidart** [comment] 2020-04-05 06:37
Thanks @rowasc!
You shouldn't composer install's on the server. 
What you describe looks just to be your modules file not being committed, and the package not knowing to load your modules.
Obviously the config file needs to be up to date etc.

**Comment by rowasc** [comment] 2020-04-05 06:43
> What you describe looks just to be your modules file not being committed, and the package not knowing to load your modules.
err no that's not the case at all.

**Comment by nWidart** [comment] 2020-04-13 17:09
Either way it's the issue of the OP, which we haven't heard from since. Because of it, I'll close this issue.

**Closed by nWidart** 2020-04-13 17:09 UTC

**Comment by masoudhosseiny** [comment] 2020-10-19 05:53
I have the same problem !

**Comment by shahalpk** [comment] 2020-11-25 10:13
delete file `bootstrap/cache/config.php` and try again.
