### ISSUE TITLE
Error '$ROUTES_LOCATION$ after update to 2.5.0

### ISSUE THREAD

**Issue by heliomoreira** [nWidart/laravel-modules#372] opened 2017-10-03 21:53 UTC
After upgrade to 2.5.0 (before i had 2.4.1) - Laravel 5.5.14 - I got this error:

Nwidart\Modules\Module::main(): Failed opening required 'C:\MAMP\htdocs\project\Modules\Catalogo$ROUTES_LOCATION$' (include_path='.;C:\php\pear')

File: start.php

if (!app()->routesAreCached()) {
    require __DIR__ . '$ROUTES_LOCATION$'; <-- Error in this line
}

In old modules, this line had: 

require __DIR__ . '/Http/routes.php';

**Comment by IllyaMoskvin** [comment] 2017-10-04 05:08
I think you need to edit your `config/modules.php`. Change this line in `stubs.replacements`:

```
'start' => ['LOWER_NAME'],
```

...to this:

```
'start' => ['LOWER_NAME', 'ROUTES_LOCATION'],
```

Related to #365, specifically commit 24badff.

**Comment by nWidart** [comment] 2017-10-04 07:00
That's correct.

**Comment by heliomoreira** [comment] 2017-10-04 08:02
Hi,

Thank you for your answer. I will change the module configuration.

However, its only happened in last version of modules.

Best regards.

**Comment by nWidart** [comment] 2017-10-04 08:03
That's because as @IllyaMoskvin pointed out, is only since the last version (2.5)

**Comment by heliomoreira** [comment] 2017-10-04 11:38
After change the module config, now I got this error:

_"Cannot declare class Modules\Crud\Providers\CrudServiceProvider, because the name is already in use"_     ---- Reported in issue: #373 

**Another issue is the url reload to** www.devdomain.x(...) after this issues.
<img width="424" alt="url" src="https://user-images.githubusercontent.com/5754523/31173796-d5a972c6-a900-11e7-935d-14b706e318a8.PNG">

**URL on install**
<img width="606" alt="nwidart-modules" src="https://user-images.githubusercontent.com/5754523/31173757-b56beab6-a900-11e7-95d4-620943889458.PNG">

**Comment by MrJoelKelly** [comment] 2017-10-04 14:40
Ran into the same problem here after changing the config value. I tried deleting the module manually, config:cache, composer dump-autoload etc. then creating the module again and still running into the same name already in use problem.

**Comment by IllyaMoskvin** [comment] 2017-10-04 14:49
@MrJoelKelly Please see issue #373 for the most likely solution. Let us know in that thread if one of the two fixes works for you, or if there's another root cause.

**Comment by nWidart** [comment] 2017-10-05 09:22
This is sadly because laravel doesn't merge configurations recursivelly.

**Comment by nWidart** [comment] 2018-01-13 20:15
I'll close this as it should be known by now 😄

**Closed by nWidart** 2018-01-13 20:15 UTC
